# Generated by Django 6.0.2 on 2026-02-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_add_image_upload_and_role_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='site_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
