# Generated by Django 6.0.2 on 2026-02-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_auth_cloudinary_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE survey_responses "
                        "ADD COLUMN IF NOT EXISTS staff_role_other varchar(200) NULL;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE survey_responses "
                        "DROP COLUMN IF EXISTS staff_role_other;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='surveyresponse',
                    name='staff_role_other',
                    field=models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
