# Generated by Django 6.0.2 on 2026-02-27 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveyresponse_staff_role_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='months_at_site',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='site_code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
