# Generated by Django 6.0.2 on 2026-02-27 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_surveyresponse_months_at_site_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='client_submission_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['submitted_by', '-submitted_at'], name='survey_resp_submitt_ba5bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['submitted_by', 'site_name', '-submitted_at'], name='survey_resp_submitt_f8fced_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['submitted_by', 'is_staffed', '-submitted_at'], name='survey_resp_submitt_03f1da_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['submitted_by', 'water_source_type', '-submitted_at'], name='survey_resp_submitt_851413_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['submitted_by', 'water_is_treated', '-submitted_at'], name='survey_resp_submitt_42d2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['submitted_by', 'used_for_drinking', '-submitted_at'], name='survey_resp_submitt_7f21be_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('submitted_by', 'client_submission_id'), name='uniq_submission_per_user_client_id'),
        ),
    ]
